app:
  name: Invest Bot
  config:
    token: ${INVEST_API_TOKEN:}
  telegram:
    token: ${TELEGRAM_BOT_TOKEN:false}

server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: logfile

logging:
  file:
    name: /tmp/app.log
